import { Injectable, signal } from '@angular/core';

export type Language = 'es' | 'jp';

@Injectable({
	providedIn: 'root',
})
export class LanguageService {
	public currentLanguage = signal<Language>('es');

	private readonly translations = {
		es: {
			operationalAnalysis: 'Análisis Operativo',
			generalSummary: 'Resumen General',
			hierarchicalAnalysis: 'Análisis Jerárquico',
			efficiencyByPart: 'Eficiencia por No. de Parte',
			managerRanking: 'Ranking de Gerentes',
			jefeRanking: 'Ranking de Jefes',
			supervisorRanking: 'Ranking de Supervisores',
			leaderRanking: 'Ranking de Líderes',
			annualTrend: 'Tendencia Anual',
			areaTrend: 'Tendencia por Área',
			managers: 'Gerentes',
			jefes: 'Jefes',
			supervisors: 'Supervisores',
			leaders: 'Líderes',
			operativity: 'Operatividad',
			topOperativity: 'Top Operatividad',
			syncingData: 'Sincronizando Datos',
			loadingData: 'Cargando datos...',
			loadingPresentation: 'Cargando datos de presentación...',
			searching: 'BUSCAR',
			presentation: 'Presentación',
			close: 'Cerrar',
			speed: 'Velocidad',
			noData: 'No se encontraron datos para los filtros seleccionados.',
			noDataPresentation: 'No hay datos disponibles para mostrar en la presentación.',
			resume: 'Reanudar Reproducción',
			pause: 'Pausar Reproducción',
			refreshingFilters: 'Actualizando opciones de filtros...',
			noFiltersData: 'No hay datos',
			startDate: 'Fecha Inicio',
			endDate: 'Fecha Fin',
			area: 'Área',
			select: 'Seleccionar',
			press: 'Prensa',
			syncing: 'Procesando...',
			startingSync: 'Iniciando sincronización...',
			expandableCardsView: 'Vista de Tarjetas Expandibles',
			list: 'Lista',
			chart: 'Gráfico',
			filterPlaceholder: 'Filtrar por nombre, área...',
			detail: 'Detalle',
			noLeaders: 'Sin líderes asignados',
			noSupervisors: 'Sin supervisores asignados',
			noJefes: 'Sin jefes de turno asignados',
			noResults: 'No se encontraron resultados',
			jefeTurno: 'Jefe de Turno',
			partNumber: 'No. de Parte',
			production: 'Producción',
			goal: 'Meta',
			pieces: 'Pzas',
			efficiency: 'Eficiencia',
			searchTable: 'Buscar...',
			operativityAnalysis: 'Análisis de Operatividad',
			totalEfficiency: 'Eficiencia Total',
			dailyTrend: 'Tendencia Diaria',
			efficiencyDetail: 'Detalle de Eficiencia',
			date: 'Fecha',
			status: 'Estado',
			excellent: 'Excelente',
			regular: 'Regular',
			low: 'Bajo',
			target: 'Objetivo',
			shift: 'Turno',
			entity: 'Entidad',
			efficiencyByDay: 'Detalle de Eficiencia por Día',
			annualTrendByArea: 'Tendencia Anual por Área',
			efficiencyTrend: 'Tendencia de Eficiencia',
			global: 'Global',
			byArea: 'Por Área',
			globalAverage: 'Promedio Global',
			noDataAvailable: 'No hay datos disponibles',
			areasLabel: 'Áreas',
		},
		jp: {
			operationalAnalysis: '稼働分析',
			generalSummary: '総合概要',
			hierarchicalAnalysis: '階層別分析',
			efficiencyByPart: '品番別効率',
			managerRanking: '部長別ランキング',
			jefeRanking: '課長別ランキング',
			supervisorRanking: '係長別ランキング',
			leaderRanking: 'リーダー別ランキング',
			annualTrend: '年間推移',
			areaTrend: 'エリア別推移',
			managers: '部長',
			jefes: '課長',
			supervisors: '係長',
			leaders: 'リーダー',
			operativity: '稼働率',
			topOperativity: '最高稼働率',
			syncingData: 'データ同期中',
			loadingData: 'データを読み込み中...',
			loadingPresentation: 'プレゼンテーションデータを読み込み中...',
			searching: '検索',
			presentation: 'プレゼンテーション',
			close: '閉じる',
			speed: '再生速度',
			noData: '選択されたフィルターのデータが見つかりませんでした。',
			noDataPresentation: 'プレゼンテーションに表示するデータがありません。',
			resume: '再生を再開',
			pause: '再生を一時停止',
			refreshingFilters: 'フィルターオプションを更新中...',
			noFiltersData: 'データなし',
			startDate: '開始日',
			endDate: '終了日',
			area: 'エリア',
			select: '選択する',
			press: 'プレス',
			syncing: '処理中...',
			startingSync: '同期を開始しています...',
			expandableCardsView: '展開可能なカード表示',
			list: 'リスト',
			chart: 'グラフ',
			filterPlaceholder: '名前、エリアでフィルター...',
			detail: '詳細',
			noLeaders: 'リーダーが割り当てられていません',
			noSupervisors: 'スーパーバイザーが割り当てられていません',
			noJefes: 'ジェフェ（課長）が割り当てられていません',
			noResults: '結果が見つかりません',
			jefeTurno: 'シフト課長',
			partNumber: '品番',
			production: '生産',
			goal: '生産目標',
			pieces: '個',
			efficiency: '生産効率',
			searchTable: '検索...',
			operativityAnalysis: '稼働率分析',
			totalEfficiency: '全体の効率',
			dailyTrend: '日次トレンド',
			efficiencyDetail: '効率詳細',
			date: '日付',
			status: 'ステータス',
			excellent: '優秀',
			regular: '普通',
			low: '低い',
			target: '目標',
			shift: 'シフト',
			entity: 'エンティティ',
			efficiencyByDay: '日次効率詳細',
			annualTrendByArea: '年次エリアトレンド',
			efficiencyTrend: '効率トレンド',
			global: 'グローバル',
			byArea: 'エリア別',
			globalAverage: 'グローバル平均',
			noDataAvailable: '利用可能なデータがありません',
			areasLabel: 'エリア',
		},
	};

	public translate(key: keyof (typeof this.translations)['es']) {
		return this.translations[this.currentLanguage()][key];
	}

	public translateDual(key: keyof (typeof this.translations)['es']) {
		const es = this.translations.es[key];
		const jp = this.translations.jp[key];
		return `${es} / ${jp}`;
	}
}
